export const expenseCategories = [
  { name: 'Advertising', slug: 'advertising', default: true },
  { name: 'Car and truck expenses', slug: 'vehicle', default: true },
  { name: 'Commissions and fees', slug: 'commissions', default: true },
  { name: 'Contract labor', slug: 'contracting', default: true },
  { name: 'Cost of goods sold', slug: 'cogs', default: true },
  { name: 'Deductible meals', slug: 'meals', default: true },
  { name: 'Depletion', slug: 'depletion', default: true },
  { name: 'Deprecation', slug: 'deprecation', default: true },
  { name: 'Employee benefit programs', slug: 'benefits', default: true },
  { name: 'Insurance (non-health)', slug: 'insurance', default: true },
  { name: 'Legal and professional services', slug: 'services', default: true },
  { name: 'Mortgage interest', slug: 'mortgage', default: true },
  { name: 'Non-business expense', slug: 'exempt', default: true },
  { name: 'Office expense', slug: 'office', default: true },
  { name: 'Other interest', slug: 'interest', default: true },
  { name: 'Other rent or lease', slug: 'lease', default: true },
  { name: 'Pension and profit-sharing plans', slug: 'plans', default: true },
  {
    name: 'Rent or lease of vehicles, machinery, and equipment',
    slug: 'equipment',
    default: true,
  },
  { name: 'Repairs and maintenance', slug: 'maintenance', default: true },
  { name: 'Software and cloud services', slug: 'software', default: false },
  { name: 'Supplies', slug: 'supplies', default: true },
  { name: 'Taxes and licenses', slug: 'taxes', default: true },
  { name: 'Travel', slug: 'travel', default: true },
  { name: 'Utilities', slug: 'utilities', default: true },
  { name: 'Wages', slug: 'wages', default: true },
]
